package: qpython
user: cpcloud

platform:
 - win-64
 - linux-64

engine:
 - python=2.7

before_script:
  - python -V

script:
  - conda build conda.recipe
  - conda install --use-local qpython pytest
  - py.test

build_targets: conda

notifications:
  email:
    recipients: ['phillip.cloud@continuum.io']
